from collections import namedtuple
from collections.abc import Iterable

import csv
import numpy as np

DataPoint = namedtuple(
    "DataPoint",
    ["parameter", "arclength", "X", "FMs", "FEs", "J_coeffs", "hill_matrix"],
)


def parse_stability_data(filename, omega=None) -> Iterable[DataPoint]:
    """Parse stability CSV data into structured records.

    Parameters
    ----------
    filename : str or path-like
        Path to the CSV file containing the stability data generated by the HillML data export script.
    omega : float, optional
        Fundamental angular frequency used to convert Floquet multipliers to
        Floquet exponents and construct the Hill matrix.
        Must be passed explicitly when the continuation parameter is not the frequency.
        If ``None`` (default), the first-column continuation parameter of each row is used.

    Yields
    ------
    DataPoint
        Named tuple with fields:
         * ``parameter``: continuation parameter values
         * ``arclength``: arc length of the point along the branch, to address each point uniquely
         * ``X``: Fourier coefficients of the periodic sol. as 1-D array, ordered [X_0, X_{c, 1}, ..., X_{c, N}, X_{s, 1}, ... X_{s, N}]
         * ``FMs``: Floquet multipliers as 1-D array,
         * ``FEs``: Floquet exponents as 1-D array,
         * ``J_coeffs``: Fourier coefficients of the system matrix as n x n x (2*N+1) array, ordered like the Fourier coeff.s of the periodic sol. * * ``hill_matrix`` real-valued Hill matrix  as 2-D array . It is the Jacobian matrix of the HBM equations in the chosen ordering.

    Notes
    -----
    For the structure of the Hill matrix see Eq.s (83)--(85) in:
    Bayer et al., "Koopman-Hill stability computation of periodic orbits in
    polynomial dynamical systems using a real-valued quadratic harmonic balance
    formulation", International Journal of Non-Linear Mechanics, 2024.
    DOI: https://doi.org/10.1016/j.ijnonlinmec.2024.104894
    """

    with open(filename, "r") as file:
        reader = csv.reader(file, delimiter=";")
        header = next(reader)

        # number of states and harmonics
        n_dof = sum(entry.startswith("FM") for entry in header[1:])
        N_harmo = (
            (sum(entry.startswith("X") for entry in header[1:]) // n_dof) - 1
        ) // 2

        if header[0] != "omega" and omega is None:
            raise ValueError(
                "The first column of the CSV file is not 'omega', so the fundamental frequency must be passed explicitly via the 'omega' argument."
            )

        for row in reader:
            # parameter, arclength
            parameter = float(row[0])
            arclength = float(row[1])

            if omega is None:
                omega = parameter

            # Floquet multipliers and Floquet exponents
            floquet_multipliers = np.array([complex(x) for x in row[2 : 2 + n_dof]])

            T = 2 * np.pi / omega
            floquet_exponents = np.log(floquet_multipliers) / T

            # Fourier coefficients of periodic solution
            X = np.array(
                [float(x) for x in row[2 + n_dof : 2 + n_dof * (2 * N_harmo + 2)]]
            )

            # Hill matrix
            hill_mat = np.array(
                [float(x) for x in row[2 + n_dof * (2 * N_harmo + 2) :]]
            )
            hill_mat = hill_mat.reshape(
                (n_dof * (2 * N_harmo + 1), n_dof * (2 * N_harmo + 1)), order="C"
            )

            # Extract Fourier coefficients of Jacobian from Hill matrix
            J_coeffs = extract_J_coeffs(hill_mat, n_dof, N_harmo)

            yield DataPoint(
                parameter,
                arclength,
                X,
                floquet_multipliers,
                floquet_exponents,
                J_coeffs,
                hill_mat,
            )


def extract_J_coeffs(hill_mat, n_dof, N_HBM):
    """Extract the Fourier coefficients of the system matrix from the Hill matrix, up to (2*N_HBM+1)-th harmonic.

    Parameters
    ----------
    hill_mat : Hill matrix in real-valued form (structured like Eq. (84) of Bayer et al., 2024)
    n_dof : int
        Number of states.
    N_HBM : int
        Number of harmonics.

    Returns
    -------
    J_coeffs : ndarray of shape (n_dof, n_dof, 4*N_HBM+1)
        Fourier coefficients of system matrix.
        J_coeffs[:,:,0] contains the coefficients of the constant term.
        J_coeffs[:,:,k] with k in range(1, 2*N_HBM+1) contains the coefficients of the cosine terms of frequency k*omega.
        J_coeffs[:,:,k] with k in range(2*N_HBM+1, 4*N_HBM+1) contains the coefficients of the sine terms of frequency (k-2*N_HBM)*omega.

    Notes
    -----
    The extraction procedure follows from Equations (84)--(85) in:
    Bayer et al., "Koopman-Hill stability computation of periodic orbits in
    polynomial dynamical systems using a real-valued quadratic harmonic balance
    formulation", International Journal of Non-Linear Mechanics, 2024.
    DOI: https://doi.org/10.1016/j.ijnonlinmec.2024.104894
    """

    # Tile the Hill matrix as in Eq. (84)
    idx_split = [n_dof, n_dof * (N_HBM + 1)]
    row_bands = np.split(hill_mat, idx_split, axis=0)
    blocks = [
        [np.split(rb, idx_split, axis=1)[j] for j in range(3)] for rb in row_bands
    ]

    # the lower-frequency Fourier coeff.s (up to N_HBM) can be found in the first row
    J_0 = blocks[0][0]
    J_c_lower = 2 * blocks[0][1].reshape((n_dof, n_dof, N_HBM), order="F")
    J_s_lower = 2 * blocks[0][2].reshape((n_dof, n_dof, N_HBM), order="F")

    # the higher-frequency Fourier coeff.s are found in the last row of the block-Hankel components Kc and Ks

    # 2*Kc according to Eq. (84) in Bayer et al., 2024
    Kc = blocks[1][1] - blocks[2][2]

    J_c_higher = Kc[-n_dof:, :].reshape((n_dof, n_dof, N_HBM), order="F")
    # no need to multiply by 2 here, because Kc already contains the factor of 2

    # 2*Ks according to Eq. (84) in Bayer et al., 2024
    Ks = blocks[1][2] + blocks[2][1]

    J_s_higher = Ks[-n_dof:, :].reshape((n_dof, n_dof, N_HBM), order="F")
    # again no need to multiply by 2

    return np.concatenate(
        [J_0[:, :, np.newaxis], J_c_lower, J_c_higher, J_s_lower, J_s_higher],
        axis=2,
    )
